#_______________________________________________________________________________
# MODIFICATION PLOTTING

#_______________________________________________________________________________
# LOAD LIBRARIES ####
library(readr)
library(tidyr)
library(stringr)
library(data.table)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(ggtext)

#_______________________________________________________________________________
# PLOTTING SETTINGS ####
my_bc_cols <- c("modified" = "#233d4d", "mismatch_C" = "#53656f",
                "fail" = "#619b8a", "mismatch_AUG" = "#fcca46",
                "deletion" = "#fe812d9f")
theme_set(theme_bw())
new_labels <- rep(c(paste0("-", 5:1), "0", paste0("+", 1:5)), 2)
names(new_labels) <- c(110:120, 560:570)

new_labels_oligos <- rep(c(paste0("-", 5:1), "0", paste0("+", 1:5)), 2)
names(new_labels_oligos) <- c(69:79, 109:119)

#_______________________________________________________________________________
# READ INPUT FILES ####
# The input files contain the basecalling context around the modified position
# in eGFP and mCherry reporters and the control oligos (-5 und +5 bases)
# The files were generated by pysam pileup in python.

samples_mpileup <- read.csv("Basecalling_error_pattern_10mer_samples.csv",
                            header = TRUE)
oligos_mpileup <- read.csv("Basecalling_error_pattern_10mer_oligos.csv",
                           header = TRUE)

#_______________________________________________________________________________
# EXTRACT % OF MISMATCHES + DORADO-MODIFIED/-FAILED + CANONICAL READS ####
## SAMPLES ####
### 1. MODIFIED ONLY (+ FAILED) ####
samples_mpileup_pct <- samples_mpileup %>%
  filter(!(condition %in% c("deletion", "mismatch_AUG"))) %>%
  group_by(ref_pos, Ref, Contig) %>%
  mutate("pct" = Nreads / sum(Nreads) * 100) %>%
  filter(condition != "canonical") %>%
  mutate("REL_POS" = as.character(new_labels[as.character(ref_pos + 1)])) %>%
  mutate("REL_POS" = factor(REL_POS, c(paste0("-", 5:1), "0",
                                       paste0("+", 1:5))))

samples_mpileup_pct_modified <- samples_mpileup_pct %>%
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  filter(condition_flat == "modified")

sample_mpileup_pct_sum <- samples_mpileup_pct %>%
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  group_by(REL_POS, Ref, Contig) %>%
  summarise(max_pct = sum(pct_sum)) %>%
  left_join(samples_mpileup_pct_modified)

g <- ggplot(samples_mpileup_pct, aes(x = REL_POS, y = pct, fill = condition)) +
  geom_bar(stat = "identity", colour = "black") +
  geom_text(data = sample_mpileup_pct_sum,
            aes(x = REL_POS, y = max_pct + 5,
                label = paste0("italic('", round(pct_sum, 2), "%", "')")),
            color = "#233d4d", size = 2, parse = TRUE, inherit.aes = FALSE) +
  facet_grid(Contig ~ Ref, scales = "free") +
  theme_bw() +
  ylim(c(0, 100)) +
  xlab("relative position") +
  ylab("% reads") +
  theme(strip.text = element_markdown()) +
  scale_fill_manual("", values = my_bc_cols) +
  theme(legend.position = "bottom", axis.ticks.x = element_blank(),
        panel.grid = element_blank()) +
  theme(strip.background = element_rect(fill = "white"))
g
ggsave("Seq_context_modified_10mer.png", g, width = 20, height = 20,
       units = "cm", dpi = 300)
ggsave("Seq_context_modified_10mer.svg", g, width = 20, height = 20,
       units = "cm", dpi = 300)
ggsave("Seq_context_modified_10mer.pdf", g, width = 20, height = 20,
       units = "cm", dpi = 300)

### 2. MODIFIED, DELETIONS, MISMATCH OTHER ####
samples_mpileup_pct_all <- samples_mpileup %>%
  group_by(ref_pos, Ref, Contig) %>%
  mutate("pct" = Nreads / sum(Nreads) * 100) %>%
  filter(condition != "canonical") %>%
  mutate("REL_POS" = as.character(new_labels[as.character(ref_pos + 1)])) %>%
  mutate("REL_POS" = factor(REL_POS, c(paste0("-", 5:1), "0",
                                       paste0("+", 1:5))))

samples_mpileup_pct_all_mod <- samples_mpileup_pct_all %>%
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  filter(condition_flat == "modified")

sample_mpileup_pct_all_sum <- samples_mpileup_pct_all %>%
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  group_by(REL_POS, Ref, Contig) %>%
  summarise(max_pct = sum(pct_sum)) %>%
  left_join(samples_mpileup_pct_all_mod)

g <- ggplot(samples_mpileup_pct_all, aes(x = REL_POS, y = pct,
                                         fill = condition)) +
  geom_bar(stat = "identity", colour = "black") +
  geom_text(data = sample_mpileup_pct_all_sum,
            aes(x = REL_POS, y = max_pct + 5,
                label = paste0("italic('", round(pct_sum, 2), "%", "')")),
            color = "#233d4d", size = 2,
            parse = TRUE, inherit.aes = FALSE) +
  facet_grid(Contig ~ Ref, scales = "free") +
  theme_bw() +
  ylim(c(0, 100)) +
  xlab("relative position") +
  ylab("% reads") +
  theme(strip.text = element_markdown()) +
  scale_fill_manual("", values = my_bc_cols) +
  theme(legend.position = "bottom", axis.ticks.x = element_blank(),
        panel.grid = element_blank()) +
  theme(strip.background = element_rect(fill = "white"))
g
ggsave("Seq_context_all_10mer.png", g, width = 20, height = 20,
       units = "cm", dpi = 300)
ggsave("Seq_context_all_10mer.svg", g, width = 20, height = 20,
       units = "cm", dpi = 300)
ggsave("Seq_context_all_10mer.pdf", g, width = 20, height = 20,
       units = "cm", dpi = 300)

## OLIGOS ####
### 1. MODIFIED ONLY (+ FAILED) ####
oligos_mpileup_pct <- oligos_mpileup %>%
  filter(!(condition %in% c("deletion", "mismatch_AUG"))) %>%
  group_by(ref_base, Ref, Contig) %>%
  mutate("pct" = Nreads / sum(Nreads)*100) %>%
  filter(condition != "canonical") %>%
  mutate("REL_POS" =
           as.character(new_labels_oligos[as.character(ref_base + 1)])) %>%
  mutate("REL_POS" = factor(REL_POS, c(paste0("-", 5:1), "0", paste0("+", 1:5))
  ))

oligos_mpileup_pct_modified <- oligos_mpileup_pct %>% 
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  filter(condition_flat == "modified")

oligos_mpileup_pct_sum <- oligos_mpileup_pct %>% 
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  group_by(REL_POS, Ref, Contig) %>%
  summarise(max_pct = sum(pct_sum)) %>%
  left_join(oligos_mpileup_pct_modified)

g <- ggplot(oligos_mpileup_pct, aes(x = REL_POS, y = pct, fill = condition)) +
  geom_bar(stat = "identity", colour = "black") +
  geom_text(data = oligos_mpileup_pct_sum,
            aes(x = REL_POS, y = max_pct + 5,
                label = paste0("italic('", round(pct_sum, 2), "%", "')")),
            color = "#233d4d", size = 2, parse = TRUE, inherit.aes = FALSE) +
  facet_grid(Contig ~ Ref, scales = "free") +
  theme_bw() +
  ylim(c(0, 105)) +
  xlab("relative position") +
  ylab("% reads") +
  theme(strip.text = element_markdown()) +
  scale_fill_manual("", values = my_bc_cols) +
  theme(legend.position = "bottom", axis.ticks.x = element_blank(),
        panel.grid = element_blank()) +
  theme(strip.background = element_rect(fill = "white"))
g
ggsave("Seq_context_modified_10mer_oligos.png", g, width = 20, height = 15,
       units = "cm", dpi = 300)
ggsave("Seq_context_modified_10mer_oligos.svg", g, width = 20, height = 15,
       units = "cm", dpi = 300)
ggsave("Seq_context_modified_10mer_oligos.pdf", g, width = 20, height = 15,
       units = "cm", dpi = 300)

### 2. MODIFIED, DELETIONS, MISMATCH OTHER ####
oligos_mpileup_pct_all <- oligos_mpileup %>%
  group_by(ref_base, Ref, Contig) %>%
  mutate("pct" = Nreads / sum(Nreads) * 100) %>%
  filter(condition != "canonical") %>%
  mutate("REL_POS" =
           as.character(new_labels_oligos[as.character(ref_base + 1)])) %>%
  mutate("REL_POS" = factor(REL_POS, c(paste0("-", 5:1), "0",
                                       paste0("+", 1:5))))

oligos_mpileup_pct_all_mod <- oligos_mpileup_pct_all %>% 
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  filter(condition_flat == "modified")

oligos_mpileup_pct_all_sum <- oligos_mpileup_pct_all %>%
  mutate("condition_flat" = ifelse(condition %in% c("modified", "mismatch_C"),
                                   "modified", condition)) %>%
  group_by(REL_POS, Ref, Contig, condition_flat) %>%
  summarise("pct_sum" = sum(pct)) %>%
  group_by(REL_POS, Ref, Contig) %>%
  summarise(max_pct = sum(pct_sum)) %>%
  left_join(oligos_mpileup_pct_all_mod)

g <- ggplot(oligos_mpileup_pct_all, aes(x = REL_POS, y = pct,
                                        fill = condition)) +
  geom_bar(stat = "identity", colour = "black") +
  geom_text(data = oligos_mpileup_pct_all_sum,
            aes(x = REL_POS, y = max_pct + 5,
                label = paste0("italic('", round(pct_sum, 2), "%", "')")),
            color = "#233d4d", size = 2, parse = TRUE, inherit.aes = FALSE) +
  facet_grid(Contig ~ Ref, scales = "free") +
  theme_bw() +
  ylim(c(0, 105)) +
  xlab("relative position") +
  ylab("% reads") +
  theme(strip.text = element_markdown()) +
  scale_fill_manual("", values = my_bc_cols) +
  theme(legend.position = "bottom", axis.ticks.x = element_blank(),
        panel.grid = element_blank()) +
  theme(strip.background = element_rect(fill = "white"))
g
ggsave("Seq_context_all_10mer_oligos.png", g, width = 20, height = 15,
       units = "cm", dpi = 300)
ggsave("Seq_context_all_10mer_oligos.svg", g, width = 20, height = 15,
       units = "cm", dpi = 300)
ggsave("Seq_context_all_10mer_oligos.pdf", g, width = 20, height = 15,
       units = "cm", dpi = 300)

print(sessionInfo())
